Repository usableprivacy/upribox, pull requests merged in 2018-05, with the labels that each got.

#132 workaround for broken ntopng repositories
  docs/source/development.rst
  roles/common/tasks/main.yml
  roles/ntopng/files/ntop.list
  roles/ntopng/tasks/main.yml
Labels: enhancement, v2

#124 Device traffic statistics
  docs/source/development.rst
  roles/common/templates/usr_local_bin_ansible-cron.j2
  roles/django/tasks/main.yml
  roles/init/tasks/main.yml
  roles/ntopng/files/ntop.list
  roles/ntopng/files/query.lua
  roles/ntopng/tasks/main.yml
  roles/upri_config/files/upri-config/lib/parser.py
  upribox_interface/devices/locale/en/LC_MESSAGES/django.mo
  upribox_interface/devices/locale/en/LC_MESSAGES/django.po
  upribox_interface/devices/templates/device_entry.html
  upribox_interface/lib/stats.py
  upribox_interface/lib/utils.py
  upribox_interface/more/locale/en/LC_MESSAGES/django.mo
  upribox_interface/more/locale/en/LC_MESSAGES/django.po
  upribox_interface/requirements.txt
  upribox_interface/settings_dev.py
  upribox_interface/settings_prod.py
  upribox_interface/setup/locale/en/LC_MESSAGES/django.po
  upribox_interface/statistics/locale/en/LC_MESSAGES/django.mo
  upribox_interface/statistics/locale/en/LC_MESSAGES/django.po
  upribox_interface/traffic/__init__.py
  upribox_interface/traffic/admin.py
  upribox_interface/traffic/apps.py
  upribox_interface/traffic/locale/en/LC_MESSAGES/django.mo
  upribox_interface/traffic/locale/en/LC_MESSAGES/django.po
  upribox_interface/traffic/migrations/__init__.py
  upribox_interface/traffic/models.py
  upribox_interface/traffic/ntopng.py
  upribox_interface/traffic/templates/__init__.py
  upribox_interface/traffic/templates/overview.html
  upribox_interface/traffic/tests.py
  upribox_interface/traffic/views.py
  upribox_interface/urls.py
  upribox_interface/vpn/locale/en/LC_MESSAGES/django.mo
  upribox_interface/vpn/locale/en/LC_MESSAGES/django.po
  upribox_interface/wlan/locale/en/LC_MESSAGES/django.mo
  upribox_interface/wlan/locale/en/LC_MESSAGES/django.po
  upribox_interface/www/locale/en/LC_MESSAGES/django.mo
  upribox_interface/www/locale/en/LC_MESSAGES/django.po
  upribox_interface/www/static/css/style.css
  upribox_interface/www/static/js/main.js
Labels: feature, v2

#129 modify backup location and frequency
  docs/source/argparser.py
  roles/upri_config/files/upri-config/lib/argparser.py
  roles/upri_config/files/upri-config/lib/backup.py
  roles/upri_config/handlers/main.yml
  roles/upri_config/tasks/main.yml
  roles/upri_config/templates/cron/backup.j2
  roles/upri_config/templates/cron/etc_cron.d_parse-user-agents.j2
Labels: v2
